# **Telecommunication Customer Churn Data Prediction**

Objective: Build a machine learning model that predicts whether a customer will churn based on demographic, service usage, and billing information.

## Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [2]:
data = pd.read_csv('../Data/cleanedData.csv')
data.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Feature Engineering

In [3]:
# Feature, target separation

y = data['Churn'].map({'Yes': 1, 'No': 0})
X = data.drop(columns=['Churn'])

In [4]:
# Tenure Buckets

tenure_bins = [0, 6, 12, 24, 48, 72, np.inf]
tenure_labels = ["0-6", "6-12", "12-24", "24-48", "48-72", "72+"]

data["tenure_bucket"] = pd.cut(
    data["tenure"],
    bins=tenure_bins,
    labels=tenure_labels,
    include_lowest=True,
    right=True
)

In [5]:
# Charges per tenure

data["charges_per_tenure"] = data["MonthlyCharges"] / (data["tenure"] + 1)

In [6]:
# Family status

data["family_status"] = (
    (data["Partner"].astype(str).str.strip().str.lower() == "yes") |
    (data["Dependents"].astype(str).str.strip().str.lower() == "yes")
).astype(int)

In [7]:
# auto payment

auto_methods = {"bank transfer (automatic)", "credit card (automatic)"}

data["is_auto_payment"] = (
    data["PaymentMethod"].astype(str)
        .str.strip()
        .str.lower()
        .isin(auto_methods)
).astype(int)

In [8]:
# YES/NO to binary

binary_map_cols = ['Partner', 'Dependents', 'PaperlessBilling']
for col in binary_map_cols:
    if col in data.columns:
        data[col] = data[col].map({'Yes': 1, 'No': 0})

In [9]:
data[
    [
        "tenure",
        "tenure_bucket",
        "MonthlyCharges",
        "charges_per_tenure",
        "Partner",
        "Dependents",
        "family_status",
        "PaymentMethod",
        "is_auto_payment",
    ]
].head()

,tenure,tenure_bucket,MonthlyCharges,charges_per_tenure,Partner,Dependents,family_status,PaymentMethod,is_auto_payment
0,1,0-6,29.85,14.925000,1,0,1,Electronic check,0
1,34,24-48,56.95,1.627143,0,0,0,Mailed check,0
2,2,0-6,53.85,17.950000,0,0,0,Mailed check,0
3,45,24-48,42.30,0.919565,0,0,0,Bank transfer (automatic),1
4,2,0-6,70.70,23.566667,0,0,0,Electronic check,0

In [10]:
# Feature Groups
numeric_features = [
    'tenure',
    'MonthlyCharges',
    'charges_per_tenure'
]

categorical_features = [
    'tenure_bucket',
    'Contract',
    'InternetService',
    'PaymentMethod',
    'gender'
]

binary_features = [
    'SeniorCitizen',
    'Partner',
    'Dependents',
    'family_status',
    'PaperlessBilling',
    'is_auto_payment'
]

## Train-Test Split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    data[numeric_features + categorical_features + binary_features],
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

## Preprocessor

In [12]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_features),
        ('bin', 'passthrough', binary_features)
    ]
)

## Model Trainings & Analysis

### Logistic Regression

In [13]:
log_reg = LogisticRegression(
    max_iter=700,
    class_weight='balanced',
    solver='liblinear'
)

In [14]:
lr_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', log_reg)
])

In [15]:
lr_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'charges_per_tenure']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['tenure_bucket', 'Contract',
                                                   'InternetService',
                                                   'PaymentMethod', 'gender']),
                                                 ('bin', 'passthrough',
                                                  ['SeniorCitizen', 'Partner',
                                                   'Dependents',
                                                   'family_status',
                                                   'PaperlessBilling',
                                                   'is_auto_payment'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=700,
                                    solver='liblinear'))])

In [17]:
y_pred = lr_model.predict(X_test)
y_prob = lr_model.predict_proba(X_test)[:, 1]

In [18]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nROC-AUC:", roc_auc_score(y_test, y_prob))

Confusion Matrix:
 [[741 294]
 [ 75 299]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.50      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.75      1409


ROC-AUC: 0.8404944586530263

### Random Forest Classifier

In [19]:
rf_classifier = RandomForestClassifier(
    n_estimators = 1000,
    random_state=42,
    class_weight='balanced'
)

In [20]:
rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', rf_classifier)
])

In [21]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'charges_per_tenure']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['tenure_bucket', 'Contract',
                                                   'InternetService',
                                                   'PaymentMethod', 'gender']),
                                                 ('bin', 'passthrough',
                                                  ['SeniorCitizen', 'Partner',
                                                   'Dependents',
                                                   'family_status',
                                                   'PaperlessBilling',
                                                   'is_auto_payment'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=1000, random_state=42))])

In [22]:
y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

In [23]:
print("Random Forest - Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nRandom Forest - Classification Report:\n", classification_report(y_test, y_pred_rf))
print("\nRandom Forest - ROC-AUC:", roc_auc_score(y_test, y_prob_rf))

Random Forest - Confusion Matrix:
 [[922 113]
 [200 174]]

Random Forest - Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.89      0.85      1035
           1       0.61      0.47      0.53       374

    accuracy                           0.78      1409
   macro avg       0.71      0.68      0.69      1409
weighted avg       0.76      0.78      0.77      1409


Random Forest - ROC-AUC: 0.8104859335038362

### XGBoost

In [24]:
neg_count = y_train.value_counts()[0]
pos_count = y_train.value_counts()[1]
scale_pos_weight_value = neg_count / pos_count

In [25]:
xgb_classifier = XGBClassifier(
    random_state=42,
    #use_label_encoder=False, # Suppress warning
    eval_metric='logloss',    # Set evaluation metric
    scale_pos_weight=scale_pos_weight_value # Handle class imbalance
)

In [26]:
xgb_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', xgb_classifier)
])

In [27]:
xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['tenure', 'MonthlyCharges',
                                                   'charges_per_tenure']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['tenure_bucket', 'Contract',
                                                   'InternetService',
                                                   'PaymentMethod', 'gender']),
                                                 ('bin', 'passthrough',
                                                  ['SeniorCitizen', 'Partner',
                                                   'Dependents',
                                                   'family_status',
                                                   'Pa...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [28]:
y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

In [29]:
print("XGBoost - Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("\nXGBoost - Classification Report:\n", classification_report(y_test, y_pred_xgb))
print("\nXGBoost - ROC-AUC:", roc_auc_score(y_test, y_prob_xgb))

XGBoost - Confusion Matrix:
 [[801 234]
 [110 264]]

XGBoost - Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.77      0.82      1035
           1       0.53      0.71      0.61       374

    accuracy                           0.76      1409
   macro avg       0.70      0.74      0.71      1409
weighted avg       0.79      0.76      0.77      1409


XGBoost - ROC-AUC: 0.8236521222454727

XGBoost performed the best overall with 88% precision and 82% ROC-AUC, followed by Random Forest, then Logistic Regression.